export const badgeFallbacks: Record<string, string> = {
    "Jan LeetCoding Challenge": "/Jan LeetCoding Challenge.png",
    "Feb LeetCoding Challenge": "/Feb LeetCoding Challenge.png",
    "Mar LeetCoding Challenge": "/Mar LeetCoding Challenge.png",
    "Apr LeetCoding Challenge": "/Apr LeetCoding Challenge.png",
    "May LeetCoding Challenge": "/May LeetCoding Challenge.png",
    "Jun LeetCoding Challenge": "/Jun LeetCoding Challenge.png",
    "Jul LeetCoding Challenge": "/Jul LeetCoding Challenge.png",
    "Aug LeetCoding Challenge": "/Aug LeetCoding Challenge.png",
    "Sep LeetCoding Challenge": "/Sep LeetCoding Challenge.png",
    "Oct LeetCoding Challenge": "/Oct LeetCoding Challenge.png",
    "Nov LeetCoding Challenge": "/Nov LeetCoding Challenge.png",
    "Dec LeetCoding Challenge": "/Dec LeetCoding Challenge.png",
    "50 Days Badge 2024": "/50 Days Badge 2024.png",
    "100 Days of Code 2024": "/100 Days of Code 2024.png",
    "200 Days of Code 2024": "/200 Days of Code 2024.png",
    "365 Days Badge": "/365 Days Badge.png",
    "500 Days Badge": "/500 Days Badge.png",
    "1000 Days Badge": "/1000 Days Badge.png",
    "2000 Days Badge": "/2000 Days Badge.png",
    "2024 Annual Badge": "/2024 Annual Badge.png",
    "2023 Annual Badge": "/2023 Annual Badge.png",
    "Guardian" : "/Guardian.png",
    "Knight" : "/Knight.png",
};
  